name: Continuous Integration (CI)

on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java Toolchain
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Add gradlew permission
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test